version: '3.8'

services:
  quote-server:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile

    ports:
       - "3000:3000"

    command: ["./index-maker", "-b", "0.0.0.0:3000", "-c", "configs", "--otlp-trace-url", "http://otel-collector:4318/v1/traces", "quote-server"]

    environment:
      RUST_LOG: info
    
    depends_on:
      otel-collector:
        condition: service_started

    restart: unless-stopped

  otel-collector:
    # Tell Docker Compose to build the image from the current context (.)
    # and specifically use the 'Dockerfile.otlp' file.
    build:
      context: .
      dockerfile: Dockerfile.otlp
    container_name: otel-collector
    ports:
      - "4318:4318" # OTLP HTTP receiver
      # - "4317:4317" # OTLP gRPC receiver
    command:
      - --config=/etc/otelcol-contrib/config.yaml # Points to the config file now embedded in the image
    restart: unless-stopped