[package]
name = "safe-math"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
# Add dependencies needed for your macro (e.g., syn, quote)
quote = "1.0.40"
syn = "2.0.101"
eyre = { workspace = true }
rust_decimal = { workspace = true }