[package]
name = "safe-math"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
# Add dependencies needed for your macro (e.g., syn, quote)
quote = { workspace = true }
syn = { workspace = true }
eyre = { workspace = true }
rust_decimal = { workspace = true }
