[package]
name = "examples"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
index-maker = { path = ".." }
binance_spot_connector_rust = { version = "1.3.0", features = ["full"] }
eyre = { workspace = true }
futures-util = "0.3.31"
itertools = { workspace = true }
rand = "0.9.1"
rust_decimal = "1.37.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["full"] }
axum = { version = "0.8", features = ["ws", "macros"] }
axum-extra = "0.10.1"
axum-server =  { version = "0.7", features = ["tls-rustls-no-provider", "tls-rustls"] }
tracing = "0.1.41"
tracing-subscriber =  { version = "0.3", features = ["env-filter"] }

[[example]]
name="binance_market_data_book_depth"
path="binance_market_data/book_depth.rs"

[[example]]
name="binance_market_data_market_data_connector"
path="binance_market_data/market_data_connector.rs"

[[example]]
name="fix_server_fix_server"
path="fix_server/fix_server.rs"
