[package]
name = "examples"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
index-maker = { path = ".." }
binance-market-data = { path = "../libs/binance-market-data" }
binance_spot_connector_rust = { version = "1.3.0", features = ["full"] }
crossbeam = { workspace = true }
eyre = { workspace = true }
futures-util = "0.3.31"
itertools = { workspace = true }
parking_lot = { workspace = true }
rand = "0.9.1"
rust_decimal = "1.37.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["full"] }
tokio-util = "0.7.15"

[[example]]
name="binance_market_data_market_data"
path="binance_market_data/market_data.rs"

[[example]]
name="binance_market_data_book_building"
path="binance_market_data/book_building.rs"

[[example]]
name="binance_market_data_market_data_connector"
path="binance_market_data/market_data_connector.rs"

[[example]]
name="fix_server_fix_server"
path="fix_server/fix_server.rs"

[[example]]
name="evm_connector"
path="evm_connector/main.rs"