[package]
name = "examples"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
index-maker = { workspace = true }
binance-market-data = { workspace = true }
binance-order-sending = { workspace = true }
binance-sdk = { workspace = true, features = ["spot"] }
chrono = { workspace = true }
crossbeam = { workspace = true }
eyre = { workspace = true }
futures-util = { workspace = true }
itertools = { workspace = true }
parking_lot = { workspace = true }
rand = { workspace = true }
rust_decimal = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true }

[[example]]
name="binance_market_data"
path="binance_market_data/market_data.rs"

[[example]]
name="binance_market_data_book"
path="binance_market_data/book_building.rs"

[[example]]
name="binance_order_sending_all_orders"
path="binance_order_sending/all_orders.rs"

[[example]]
name="binance_order_sending_wss_sample"
path="binance_order_sending/wss_sample.rs"

[[example]]
name="binance_order_sending"
path="binance_order_sending/main.rs"

[[example]]
name="fix_server_fix_server"
path="fix_server/fix_server.rs"
