receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_size: 100
    timeout: 10s

exporters:
  otlp/elastic:
    endpoint: "https://index-maker-ded0ed.ingest.us-east-1.aws.elastic.cloud:443"
    headers:
      Authorization: ${env:ELASTIC_API_KEY}
    tls:
      insecure: false
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/elastic]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/elastic]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/elastic]