name: Docker Image CI

on:
  push:
    branches: [ "staging" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag
        run: echo "IMAGE_TAG=index-maker:1.5_$(date +%s)" >> $GITHUB_ENV
        
      - name: Build and load the Docker image
        run: docker buildx build . --platform linux/amd64 --file Dockerfile --tag ${{ env.IMAGE_TAG }} --load
      
      - name: Save Docker image to a tar file
        run: docker save -o index-maker.tar ${{ env.IMAGE_TAG }}
      
      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-artifact
          path: index-maker.tar
          retention-days: 7
